export const DESIGNATIONS = [
  'Account Executive',
  'Account Manager',
  'Accountant',
  'Administrative Assistant',
  'Analyst',
  'Android Developer',
  'Angular Developer',
  'Application Developer',
  'Architect',
  'Art Director',
  'Associate',
  'Associate Director',
  'Associate Manager',
  'Assistant Manager',
  'Assistant Vice President',
  'Backend Developer',
  'Business Analyst',
  'Business Development Executive',
  'Business Development Manager',
  'Business Intelligence Analyst',
  'CEO',
  'CFO',
  'CMO',
  'COO',
  'CTO',
  'Chief Executive Officer',
  'Chief Financial Officer',
  'Chief Marketing Officer',
  'Chief Operating Officer',
  'Chief Technology Officer',
  'Cloud Architect',
  'Cloud Engineer',
  'Consultant',
  'Content Manager',
  'Content Writer',
  'Customer Success Manager',
  'Data Analyst',
  'Data Engineer',
  'Data Scientist',
  'Database Administrator',
  'Designer',
  'DevOps Engineer',
  'Director',
  'Engineering Manager',
  'Executive',
  'Executive Director',
  'Executive Vice President',
  'Finance Manager',
  'Financial Analyst',
  'Frontend Developer',
  'Full Stack Developer',
  'General Manager',
  'Graphic Designer',
  'HR Manager',
  'Human Resources Manager',
  'iOS Developer',
  'IT Manager',
  'Java Developer',
  'Lead Developer',
  'Lead Engineer',
  'Machine Learning Engineer',
  'Marketing Executive',
  'Marketing Manager',
  'Mobile Developer',
  'Node.js Developer',
  'Operations Manager',
  'Principal Engineer',
  'Product Manager',
  'Program Manager',
  'Project Manager',
  'Python Developer',
  'Quality Assurance Engineer',
  'React Developer',
  'Regional Manager',
  'Sales Executive',
  'Sales Manager',
  'Security Engineer',
  'Senior Analyst',
  'Senior Consultant',
  'Senior Developer',
  'Senior Engineer',
  'Senior Manager',
  'Senior Vice President',
  'Software Architect',
  'Software Developer',
  'Software Engineer',
  'Solution Architect',
  'Supply Chain Manager',
  'System Administrator',
  'System Engineer',
  'Technical Architect',
  'Technical Lead',
  'UI Designer',
  'UI/UX Designer',
  'UX Designer',
  'Vice President',
  'Vue.js Developer',
  'Web Developer',
  'Zonal Manager'
];
